export default {
    FETCHED_HOTELS: 'FETCHED_HOTELS',
    SET_HOTEL: 'SET_HOTEL',
    FETCHED_HOTEL_DETAIL:'FETCHED_HOTEL_DETAIL',
    FETCHED_HOTEL_ROOMS:'FETCHED_HOTEL_ROOMS',
    REFRESHING: 'REFRESHING',
    ERROR_MESSAGE: 'ERROR_MESSAGE',
    SET_ROOM:'SET_ROOM'
  };